export type SecretKeyword = {
  id: string
  keyword: string
  projectSlug: string
  syntaxRole: "variable" | "function" | "string" | "comment" | "keyword" | "class"
}

export type CodeSnippet = {
  id: string
  filename: string
  language: string
  lines: string[]
  secrets: (SecretKeyword & { line: number })[]
}

export const snippets: CodeSnippet[] = [
  {
    id: "s1",
    filename: "query_engine.py",
    language: "python",
    lines: [
      "import oracledb",
      "from anthropic import Anthropic",
      "",
      "class SankhyaBI:",
      "    def __init__(self, dsn: str):",
      '        self.pool = oracledb.create_pool(dsn=dsn, min=2, max=10)',
      "        self.client = Anthropic()",
      "",
      "    def ask_oraculo(self, question: str) -> dict:",
      '        prompt = f"Converta para SQL Oracle: {question}"',
      "        response = self.client.messages.create(",
      '            model="claude-sonnet-4-20250514",',
      '            messages=[{"role": "user", "content": prompt}]',
      "        )",
      "        sql = response.content[0].text",
      "        return self._execute_query(sql)",
    ],
    secrets: [{ id: "oraculo", keyword: "oraculo", projectSlug: "oraculo", line: 8, syntaxRole: "function" }],
  },
  {
    id: "s2",
    filename: "deploy.sh",
    language: "bash",
    lines: [
      "#!/bin/bash",
      "set -euo pipefail",
      "",
      'echo "Pulling latest changes..."',
      "git pull origin main",
      "",
      'echo "Building wms_project..."',
      "docker compose -f docker-compose.prod.yml build",
      "docker compose -f docker-compose.prod.yml up -d",
      "",
      "# Health check",
      'until curl -sf http://localhost:5000/health; do',
      "  sleep 2",
      "done",
      'echo "Deploy complete."',
    ],
    secrets: [{ id: "wms", keyword: "wms_project", projectSlug: "wms-project", line: 6, syntaxRole: "string" }],
  },
  {
    id: "s3",
    filename: "scheduler.ts",
    language: "javascript",
    lines: [
      'import cron from "node-cron"',
      'import { SankhyaAPI } from "./sankhya"',
      "",
      "const api = new SankhyaAPI(process.env.SANKHYA_URL!)",
      "",
      "// Criar OPs automaticamente a cada 30min",
      'cron.schedule("*/30 * * * *", async () => {',
      "  const pendentes = await api.getPlanningTable()",
      "  for (const item of pendentes) {",
      "    await api.programador_create_op({",
      "      codprod: item.CODPROD,",
      "      quantidade: item.QTDPLAN,",
      "      prioridade: item.PRIOR,",
      "    })",
      "  }",
      "})",
    ],
    secrets: [{ id: "programador", keyword: "programador", projectSlug: "programador", line: 9, syntaxRole: "function" }],
  },
  {
    id: "s4",
    filename: "docker-compose.yml",
    language: "yaml",
    lines: [
      "version: '3.8'",
      "services:",
      "  producao_suite:",
      "    build: ./backend",
      "    ports:",
      '      - "8080:8080"',
      "    environment:",
      "      - ORACLE_DSN=${ORACLE_DSN}",
      "      - REDIS_URL=redis://cache:6379",
      "    depends_on:",
      "      - cache",
      "      - oracle",
      "  cache:",
      "    image: redis:7-alpine",
      "    restart: unless-stopped",
    ],
    secrets: [{ id: "producao", keyword: "producao_suite", projectSlug: "producao", line: 2, syntaxRole: "variable" }],
  },
  {
    id: "s5",
    filename: "analytics.py",
    language: "python",
    lines: [
      "import streamlit as st",
      "import plotly.express as px",
      "from data_loader import load_production_data",
      "",
      "st.set_page_config(layout='wide')",
      "st.title('Production BI Dashboard')",
      "",
      "df = load_production_data()",
      "col1, col2 = st.columns(2)",
      "",
      "with col1:",
      "    fig = px.bar(df, x='produto', y='iaprod_efficiency')",
      "    st.plotly_chart(fig, use_container_width=True)",
      "",
      "with col2:",
      "    st.metric('OEE Geral', f\"{df['oee'].mean():.1%}\")",
    ],
    secrets: [{ id: "iaprod", keyword: "iaprod", projectSlug: "iaprod", line: 11, syntaxRole: "variable" }],
  },
  {
    id: "s6",
    filename: "routes/orders.ts",
    language: "javascript",
    lines: [
      'import { Router } from "express"',
      'import { zustandStore } from "../store"',
      "",
      "const router = Router()",
      "",
      "router.post('/inplanta/orders', async (req, res) => {",
      "  const { items, clientId } = req.body",
      "  const session = await getSankhyaSession()",
      "  const order = await session.createOrder({",
      "    items,",
      "    clientId,",
      "    origin: 'mobile-sales',",
      "  })",
      "  res.json({ orderId: order.NUNOTA })",
      "})",
    ],
    secrets: [{ id: "inplanta", keyword: "inplanta", projectSlug: "inplanta", line: 5, syntaxRole: "string" }],
  },
  {
    id: "s7",
    filename: "services/marketplace.go",
    language: "go",
    lines: [
      "package services",
      "",
      "import (",
      '    "context"',
      '    "github.com/gofiber/fiber/v2"',
      ")",
      "",
      "type ChaveiroGO struct {",
      "    db     *pgxpool.Pool",
      "    redis  *redis.Client",
      "    socket *socketio.Server",
      "}",
      "",
      "func (s *ChaveiroGO) FindNearby(ctx context.Context, lat, lng float64) ([]Provider, error) {",
      '    return s.db.Query(ctx, "SELECT * FROM providers WHERE ST_DWithin(location, $1, 5000)", point(lat, lng))',
      "}",
    ],
    secrets: [{ id: "chaveirogo", keyword: "ChaveiroGO", projectSlug: "chaveirogo", line: 7, syntaxRole: "class" }],
  },
  {
    id: "s8",
    filename: "agents/prospector.js",
    language: "javascript",
    lines: [
      'const { WhatsAppClient } = require("whatsapp-web.js")',
      'const { GoogleMapsAPI } = require("./scraper")',
      "",
      "class LeadEra {",
      "  constructor(providers) {",
      "    this.ai = providers // gemini, openai, anthropic",
      "    this.whatsapp = new WhatsAppClient()",
      "  }",
      "",
      "  async prospect(query, city) {",
      "    const leads = await GoogleMapsAPI.search(query, city)",
      "    for (const lead of leads) {",
      "      const msg = await this.ai.generate(lead.profile)",
      "      await this.whatsapp.send(lead.phone, msg)",
      "    }",
      "  }",
      "}",
    ],
    secrets: [{ id: "leadera", keyword: "LeadEra", projectSlug: "leadera", line: 3, syntaxRole: "class" }],
  },
  {
    id: "s9",
    filename: "bluetooth/sensor.kt",
    language: "kotlin",
    lines: [
      "package com.plante.iot.sensors",
      "",
      "import android.bluetooth.BluetoothGatt",
      "",
      "class PlanteSensor(private val gatt: BluetoothGatt) {",
      "    fun readMoisture(): Float {",
      "        val characteristic = gatt.getService(SOIL_SERVICE_UUID)",
      "            ?.getCharacteristic(MOISTURE_UUID)",
      "        return characteristic?.value?.let {",
      "            ByteBuffer.wrap(it).float",
      "        } ?: -1f",
      "    }",
      "",
      "    companion object {",
      '        val SOIL_SERVICE_UUID = UUID.fromString("0000180d-0000-1000-8000-00805f9b34fb")',
      "    }",
      "}",
    ],
    secrets: [{ id: "plante", keyword: "PlanteSensor", projectSlug: "plante", line: 4, syntaxRole: "class" }],
  },
  {
    id: "s10",
    filename: "scene.html",
    language: "html",
    lines: [
      "<!DOCTYPE html>",
      "<html>",
      "<head>",
      '  <script src="https://aframe.io/releases/1.4.0/aframe.min.js"></script>',
      "</head>",
      "<body>",
      '  <a-scene vasap-viewer embedded>',
      '    <a-asset-item id="model" src="/models/vaso.glb"></a-asset-item>',
      '    <a-entity gltf-model="#model" position="0 1 -3"',
      '             animation="property: rotation; to: 0 360 0; loop: true; dur: 8000">',
      "    </a-entity>",
      '    <a-sky color="#1a1a2e"></a-sky>',
      "  </a-scene>",
      "</body>",
      "</html>",
    ],
    secrets: [{ id: "vasap", keyword: "vasap", projectSlug: "vasap-ar", line: 6, syntaxRole: "variable" }],
  },
  {
    id: "s11",
    filename: "monitor.js",
    language: "javascript",
    lines: [
      'const axios = require("axios")',
      'const { EvolutionAPI } = require("./whatsapp")',
      "",
      "async function checkSankhyaUptime() {",
      "  try {",
      '    const res = await axios.get(process.env.SANKHYA_URL + "/health", {',
      "      timeout: 5000,",
      "    })",
      "    if (res.status !== 200) throw new Error(`Status ${res.status}`)",
      "  } catch (err) {",
      '    await EvolutionAPI.send(process.env.ALERT_GROUP, `[DOWN] Sankhya offline: ${err.message}`)',
      "  }",
      "}",
      "",
      'setInterval(checkSankhyaUptime, 60_000)',
    ],
    secrets: [{ id: "uptime", keyword: "checkSankhyaUptime", projectSlug: "down-notify", line: 3, syntaxRole: "function" }],
  },
  {
    id: "s12",
    filename: "auto_op.py",
    language: "python",
    lines: [
      "import schedule",
      "from sankhya_api import SankhyaClient",
      "",
      "client = SankhyaClient()",
      "",
      "def auto_programacao_run():",
      '    rows = client.query("SELECT * FROM AD_PLAN WHERE STATUS = \'P\'")',
      "    for row in rows:",
      "        op = client.create_op(",
      "            codprod=row['CODPROD'],",
      "            qtd=row['QTDPLAN'],",
      "        )",
      "        client.update_plan_status(row['ID'], 'PROCESSED')",
      "        print(f'OP {op.IDIPROC} criada com sucesso')",
      "",
      "schedule.every(15).minutes.do(auto_programacao_run)",
    ],
    secrets: [{ id: "auto", keyword: "auto_programacao", projectSlug: "auto-programacao", line: 5, syntaxRole: "function" }],
  },
  {
    id: "s13",
    filename: "tracking/api.py",
    language: "python",
    lines: [
      "from flask import Flask, request, jsonify",
      "from auth import validate_cpf_cnpj",
      "",
      "app = Flask(__name__)",
      "",
      "@app.route('/rastreio/status', methods=['POST'])",
      "def order_tracking_portal():",
      "    doc = request.json.get('document')",
      "    if not validate_cpf_cnpj(doc):",
      "        return jsonify(error='Documento invalido'), 400",
      '    orders = db.query("SELECT * FROM TGFCAB WHERE CGC_CPF = :doc", doc=doc)',
      "    return jsonify(orders=[serialize(o) for o in orders])",
    ],
    secrets: [{ id: "rastreio", keyword: "order_tracking_portal", projectSlug: "pagina-rastreio", line: 6, syntaxRole: "function" }],
  },
  {
    id: "s14",
    filename: "finance/stream.ts",
    language: "javascript",
    lines: [
      'import WebSocket from "ws"',
      "",
      "const FINNHUB_KEY = process.env.FINNHUB_API_KEY",
      "",
      "class OnlyInvest {",
      "  private ws: WebSocket",
      "",
      "  connect() {",
      "    this.ws = new WebSocket(`wss://ws.finnhub.io?token=${FINNHUB_KEY}`)",
      "    this.ws.on('message', (data) => {",
      "      const { type, data: trades } = JSON.parse(data.toString())",
      "      if (type === 'trade') this.updatePrices(trades)",
      "    })",
      "  }",
      "}",
    ],
    secrets: [{ id: "onlyinvest", keyword: "OnlyInvest", projectSlug: "onlyinvest", line: 4, syntaxRole: "class" }],
  },
  {
    id: "s15",
    filename: "garden/identify.js",
    language: "javascript",
    lines: [
      "async function identifyPlant(imageBase64) {",
      "  const response = await fetch('https://my-api.plantnet.org/v2/identify', {",
      "    method: 'POST',",
      "    headers: { 'Content-Type': 'application/json' },",
      "    body: JSON.stringify({",
      "      images: [imageBase64],",
      "      organs: ['leaf'],",
      "      vasap_garden_key: process.env.PLANTNET_KEY,",
      "    })",
      "  })",
      "  const data = await response.json()",
      "  return data.results[0]?.species?.scientificName",
      "}",
    ],
    secrets: [{ id: "garden", keyword: "vasap_garden", projectSlug: "vasap-garden", line: 7, syntaxRole: "variable" }],
  },
  {
    id: "s16",
    filename: "packing/optimizer.ts",
    language: "javascript",
    lines: [
      'import { GeminiAPI } from "@google/generative-ai"',
      "",
      "interface CargoItem { w: number; h: number; d: number; weight: number }",
      "",
      "async function cargo_optimizer(items: CargoItem[], truckDims: Dims) {",
      "  const gemini = new GeminiAPI(process.env.GEMINI_KEY!)",
      "  const prompt = `Optimize 3D bin packing for ${items.length} items",
      "    in a ${truckDims.w}x${truckDims.h}x${truckDims.d}cm container.`",
      "  const result = await gemini.generateContent(prompt)",
      "  return JSON.parse(result.response.text())",
      "}",
    ],
    secrets: [{ id: "cargo", keyword: "cargo_optimizer", projectSlug: "cargo-optimizer", line: 4, syntaxRole: "function" }],
  },
  {
    id: "s17",
    filename: "migration.py",
    language: "python",
    lines: [
      "import os",
      "import shutil",
      "from pathlib import Path",
      "",
      "SKIP_FILES = {'NTUSER.DAT', 'ntuser.dat.LOG', 'desktop.ini'}",
      "",
      "def windows_profile_migrator(src_user: str, dst_user: str):",
      "    src = Path(f'C:/Users/{src_user}')",
      "    dst = Path(f'C:/Users/{dst_user}')",
      "    if src_user == os.getlogin():",
      "        raise RuntimeError('Nao pode migrar usuario logado')",
      "    for item in src.rglob('*'):",
      "        if item.name not in SKIP_FILES:",
      "            dest = dst / item.relative_to(src)",
      "            dest.parent.mkdir(parents=True, exist_ok=True)",
      "            shutil.copy2(item, dest)",
    ],
    secrets: [{ id: "migrator", keyword: "windows_profile_migrator", projectSlug: "migrar-dados", line: 6, syntaxRole: "function" }],
  },
  {
    id: "s18",
    filename: "contempo.html",
    language: "html",
    lines: [
      '<a-scene vasap_contempo embedded>',
      '  <a-assets>',
      '    <a-asset-item id="vaso" src="/models/contempo.glb"></a-asset-item>',
      '  </a-assets>',
      "",
      '  <a-entity light="type: spot; intensity: 2; angle: 45"',
      '            position="2 4 1"></a-entity>',
      '  <a-entity gltf-model="#vaso"',
      '            animation="property: rotation; to: 0 360 0; dur: 12000; loop: true">',
      '  </a-entity>',
      '  <a-plane rotation="-90 0 0" width="10" height="10"',
      '           material="color: #1a1a2e; metalness: 0.8"></a-plane>',
      "</a-scene>",
    ],
    secrets: [{ id: "contempo", keyword: "vasap_contempo", projectSlug: "vasap-contempo", line: 0, syntaxRole: "variable" }],
  },
  {
    id: "s19",
    filename: "tasks/workspace.py",
    language: "python",
    lines: [
      "from flask import Blueprint",
      "from sqlalchemy import select",
      "from models import Workspace, Task, Project",
      "",
      "pulsar_bp = Blueprint('pulsar', __name__)",
      "",
      "@pulsar_bp.route('/workspaces/<int:ws_id>/tasks')",
      "def list_tasks(ws_id):",
      "    stmt = select(Task).where(Task.workspace_id == ws_id)",
      "    tasks = db.session.execute(stmt).scalars().all()",
      "    return jsonify([t.to_graph_node() for t in tasks])",
    ],
    secrets: [{ id: "pulsar", keyword: "pulsar", projectSlug: "pulsar", line: 4, syntaxRole: "variable" }],
  },
  {
    id: "s20",
    filename: "dtf_generator.js",
    language: "javascript",
    lines: [
      "function generateHardskillsSVG(techName, logoPath) {",
      "  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')",
      "  svg.setAttribute('viewBox', '0 0 300 300')",
      "",
      "  // Layer 1: CMYK base",
      "  const cmyk = createLayer('cmyk', logoPath)",
      "  // Layer 2: White underbase",
      "  const white = createLayer('white', logoPath, { fill: '#FFFFFF' })",
      "  // Layer 3: UV varnish (raised effect)",
      "  const uv = createLayer('uv-varnish', logoPath, { opacity: 0.9 })",
      "",
      "  svg.append(cmyk, white, uv)",
      "  return new XMLSerializer().serializeToString(svg)",
      "}",
    ],
    secrets: [{ id: "hardskills", keyword: "Hardskills", projectSlug: "colaai", line: 0, syntaxRole: "function" }],
  },
]

export const totalSecrets = snippets.reduce((acc, s) => acc + s.secrets.length, 0)
