import { promises as fs } from "fs";
import path from "path";

// Only real source code: configs (json/yaml/toml/xml), docs (md), and IaC (tf/dockerfile)
// are excluded because they're either auto-generated or not "code I wrote".
const CODE_EXTENSIONS = new Set([
  ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
  ".py", ".pyw",
  ".go",
  ".rs",
  ".java", ".kt", ".scala",
  ".c", ".h", ".cpp", ".hpp", ".cc", ".cxx",
  ".cs",
  ".rb",
  ".php",
  ".swift",
  ".m", ".mm",
  ".sh", ".bash", ".zsh", ".fish",
  ".sql",
  ".html", ".htm",
  ".css", ".scss", ".sass", ".less",
  ".vue", ".svelte", ".astro",
  ".lua",
  ".r", ".R",
  ".dart",
  ".ex", ".exs",
  ".elm",
  ".clj", ".cljs",
  ".hs",
  ".ml",
  ".pl",
  ".groovy",
]);

const SKIP_DIRS = new Set([
  // dependencies / virtualenvs
  "node_modules", "vendor", "__pycache__", ".venv", "venv", "env",
  "Pods", ".cargo", ".terraform",
  // VCS / IDE
  ".git", ".idea", ".vscode",
  // build outputs
  ".next", ".nuxt", "dist", "build", "out", "target", "bin", "obj",
  ".svelte-kit", ".gradle",
  // caches
  ".pytest_cache", ".mypy_cache", ".ruff_cache", ".turbo",
  "coverage", ".cache", ".parcel-cache",
  // static assets (not code I wrote)
  "public", "static", "assets",
  // auto-generated by ORMs / frameworks
  "migrations",
]);

// Path fragments that, if present anywhere in the relative path, cause skip.
// Used to skip generated UI libraries inside arbitrary src/ structures.
const SKIP_PATH_FRAGMENTS = [
  "components/ui",   // shadcn/ui generated components
  "src/components/ui",
  "lib/ui",
  "app/api/auth/[...nextauth]", // NextAuth boilerplate
];

const SKIP_FILE_PATTERNS = [
  // minified / bundled
  /\.min\.(js|css)$/i,
  /\.bundle\.(js|css)$/i,
  // lock files
  /-lock\.(json|yaml|yml)$/i,
  /pnpm-lock\.yaml$/i,
  /yarn\.lock$/i,
  /package-lock\.json$/i,
  /poetry\.lock$/i,
  /Cargo\.lock$/i,
  /go\.sum$/i,
  // configs (covers next.config.*, tailwind.config.*, vite.config.*, postcss.config.*, etc)
  /\.config\.(js|cjs|mjs|ts)$/i,
  /^tsconfig.*\.json$/i,
  /^components\.json$/i,
  /^\.eslintrc.*/i,
  /^\.prettierrc.*/i,
  /^eslint\.config\.(js|cjs|mjs|ts)$/i,
  /^prettier\.config\.(js|cjs|mjs|ts)$/i,
  // env / dotfiles that are typically not code
  /^\.env(\..*)?$/i,
  /^\.gitignore$/i,
  /^\.gitattributes$/i,
  /^\.dockerignore$/i,
  /^\.editorconfig$/i,
  /^\.npmrc$/i,
  /^\.nvmrc$/i,
  // docs / license
  /\.md$/i,
  /^LICENSE.*$/i,
  /^CHANGELOG.*$/i,
  /^README.*$/i,
  // generated typings
  /^next-env\.d\.ts$/i,
  /\.generated\.(ts|js|tsx|jsx)$/i,
];

const MAX_FILE_BYTES = 2 * 1024 * 1024;

function shouldSkipFile(name) {
  return SKIP_FILE_PATTERNS.some((re) => re.test(name));
}

function shouldSkipPath(relPath) {
  const normalized = relPath.replaceAll(path.sep, "/");
  return SKIP_PATH_FRAGMENTS.some((frag) => normalized.includes(frag));
}

async function countLinesInFile(filePath) {
  try {
    const stat = await fs.stat(filePath);
    if (stat.size > MAX_FILE_BYTES) return 0;
    const content = await fs.readFile(filePath, "utf-8");
    if (content.length === 0) return 0;
    let count = 1;
    for (let i = 0; i < content.length; i++) {
      if (content.charCodeAt(i) === 10) count++;
    }
    if (content.charCodeAt(content.length - 1) === 10) count--;
    return count;
  } catch {
    return 0;
  }
}

export async function countProjectLines(projectPath) {
  let totalLines = 0;
  let fileCount = 0;
  let lastModified = 0;

  async function walk(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.name.startsWith(".")) continue;
      const full = path.join(dir, entry.name);
      const rel = path.relative(projectPath, full);
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        if (shouldSkipPath(rel)) continue;
        await walk(full);
      } else if (entry.isFile()) {
        if (shouldSkipFile(entry.name)) continue;
        if (shouldSkipPath(rel)) continue;
        const ext = path.extname(entry.name).toLowerCase();
        if (!CODE_EXTENSIONS.has(ext)) continue;
        const lines = await countLinesInFile(full);
        totalLines += lines;
        fileCount++;
        try {
          const st = await fs.stat(full);
          if (st.mtimeMs > lastModified) lastModified = st.mtimeMs;
        } catch { /* ignore */ }
      }
    }
  }

  await walk(projectPath);
  return {
    lines: totalLines,
    fileCount,
    lastModified: lastModified > 0 ? new Date(lastModified).toISOString() : new Date().toISOString(),
  };
}
